name: Deprecated Code Detection

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  deprecated-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: backend/dama/requirements.txt

      - name: Install dependencies
        run: |
          cd backend/dama
          pip install --break-system-packages -r requirements.txt

      - name: Install deprecation tools
        run: |
          pip install --break-system-packages flake8 flake8-deprecated

      - name: Run deprecated code detection
        run: |
          cd backend/dama
          flake8 --select=W601,W602,W603,W604 .